### ISSUE TITLE
dark mode in admin helper mode is broken

### ISSUE THREAD

**Issue by hawka97** [Mica-Technologies/Minecraft-Forge-Launcher#24]
Dark mode/light mode switching is broken in the admin helper mode UI. Most text/labels are not very visible in some scenarios.

**Comment by rinrincodes** [comment]
Did you include the dark mode CSS? I can remember when you started work on the admin helper mode dark mode wasn't quite ready back when you first worked on it. Maybe checking that first would help otherwise you might need to check the classes a bit more that do the actual dark mode switching and see if there already present in the code of the admin helper window.

**Comment by hawka97** [comment]
The CSS is automatically included. Each GUI class is a sub-class of a master GUI class I made that controls things like loading CSS, handling dark/light mode change, showing, hiding, etc

**Comment by hawka97** [comment]
fixed: 216bba9eadcf9f6259aee978e3d785f65c04975c
